# Generated by Django 6.0.2 on 2026-03-11 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qdeploy', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='repo',
            new_name='repo_url',
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
